# Generated by Django 4.0.4 on 2022-05-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_remember', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remember',
            name='img',
            field=models.ImageField(blank=True, upload_to='places_remember/images'),
        ),
    ]
